spring.application.name=Springboot_BookStore

spring.datasource.url=jdbc:mysql://localhost:3306/BookStore?createDatabaseIfNotExist=true
spring.datasource.username= root
spring.datasource.password= root
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

jwt.secretKey=asdfhads9f67as98dfyaisudhfa98s67dfy89aishudfuays89dfyasi8df7asdf87987g98a7sg986a89sdf7y


